### ISSUE TITLE
Cancel on remove all data still wipes out everything

### ISSUE THREAD

**Issue by signalw** [dconlisk/bristol-stool-chart-flutter-app#1]
Thanks for opensourcing this nice app! But I ran into this bug when I was playing around to see if I can remove a single stool entry. To reproduce:

1. add some data
2. go to settings
3. click "DELETE DATA" -> there should be a window popping up confirming if you wish to continue
4. click "CANCEL"
5. switch back to graph -> all data has been removed

I'm using iOS13.5.1

**Comment by dconlisk** [comment]
Ah, well spotted, thanks for raising this. I have confirmed this on the Android version of the app as well.

**Comment by dconlisk** [comment]
This has been fixed in the latest release, v2.0.1 (18)
